# Generated by Django 4.0 on 2023-05-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название школы (образовательной организации)', max_length=900)),
                ('info', models.CharField(db_index=True, help_text='Информация о школе', max_length=900)),
                ('profile_pic', models.ImageField(blank=True, help_text='Аватарка школы', upload_to='profile_pic')),
                ('file', models.FileField(blank=True, help_text='Скан подтверждающего документа', upload_to='products/%Y/%m/%d')),
                ('available', models.BooleanField(default=True, help_text='Прошла ли верификацию?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название курса.', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.CharField(blank=True, help_text='Краткое описание курса (опционально).', max_length=77)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена курса.', max_digits=10)),
                ('stock', models.PositiveIntegerField(help_text='Доступное количество мест на курсе.')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Категория курса.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CourseSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(help_text='Продукт', on_delete=django.db.models.deletion.CASCADE, related_name='course_products', to='shop.product')),
                ('school', models.ForeignKey(help_text='Школа', on_delete=django.db.models.deletion.CASCADE, related_name='course_schools', to='shop.school')),
            ],
            options={
                'verbose_name': 'CourseSchool',
                'verbose_name_plural': 'CourseSchools',
                'db_table': 'courseschools',
                'unique_together': {('product', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(help_text='Продукт', on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='shop.product')),
                ('user', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='basket_users', to='shop.user')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'db_table': 'baskets',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
